const lambdaNamespace = 'AWS/Lambda';
const apiGatewayNamespace = 'AWS/ApiGateway';

module.exports = {
  functionInvocations: {
    namespace: lambdaNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: 'Invocations',
    threshold: 100,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold',
  },
  functionErrors: {
    namespace: lambdaNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: 'Errors',
    threshold: 1,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold',
  },
  functionDuration: {
    namespace: lambdaNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: 'Duration',
    threshold: 500,
    statistic: 'Average',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold',
  },
  functionThrottles: {
    namespace: lambdaNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: 'Throttles',
    threshold: 1,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold',
  },
  '4XXErrors': {
    namespace: apiGatewayNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: '4XXError',
    threshold: 1,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold'
  },
  '5XXErrors': {
    namespace: apiGatewayNamespace,
    enabled: true,
    actionsEnabled: true,
    type: 'static',
    metric: '5XXError',
    threshold: 1,
    statistic: 'Sum',
    period: 60,
    evaluationPeriods: 1,
    datapointsToAlarm: 1,
    comparisonOperator: 'GreaterThanOrEqualToThreshold'
  },
};
